#eureka:
#  serviceUrl:
#    defaultZone: http://localhost:8761/eureka
#  instance:
#    hostName: localhost
#  registerWithEureka: true
#  fetchRegistry: true

spring:
  cloud:
    config:
      uri : http://localhost:9095