spring:
  application:
    name:
      cloud-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Reemasqt/cloud-config

  eureka:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostName: localhost
    registerWithEureka: true
    fetchRegistry: true